export const GRID_CONFIG = {
  COLUMNS: 12,
  ROWS: 24,
  CELL_WIDTH: 80,
  CELL_HEIGHT: 90,
  TOTAL_CELLS: 288
};

export const VIEWPORT = {
  WIDTH: GRID_CONFIG.COLUMNS * GRID_CONFIG.CELL_WIDTH,
  HEIGHT: GRID_CONFIG.ROWS * GRID_CONFIG.CELL_HEIGHT
};